name: Check for New Stackoverflow Questions and Add to Orbit
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
        - "algolia"
        - "instantsearch"
    steps:
      - run: npx @orbit-love/stackoverflow --questions --answers --hours=300 --tag="${{ matrix.tag }}"
        env:
          ORBIT_WORKSPACE_ID: ${{ secrets.ORBIT_WORKSPACE_ID }}
          ORBIT_API_KEY: ${{ secrets.ORBIT_API_KEY }}
          STACK_APPS_KEY: ${{ secrets.STACK_APPS_KEY }}

