on: push
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
        - "algolia"
        - "instantsearch"
    steps:
      - run: echo "${{ matrix.tag }} - ${{ env.TEST_VAR }}"
      - run: npx @orbit-love/stackoverflow --questions --answers --hours=300 --tag ${{ matrix.tag }}
        env:
          TEST_VAR: "hi"