on: push
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
        - "algolia"
        - "instantsearch"
    steps:
      - run: echo "${{ matrix.tag }}"
      - run: npx @orbit-love/stackoverflow --questions --answers --hours=300 --tag ${{ matrix.tag }}
        env:
          ORBIT_WORKSPACE_ID: "algolia"
          ORBIT_API_KEY: ${{ secrets.ORBIT_API_KEY }}
          STACK_APPS_KEY: ${{ secrets.STACK_APPS_KEY }}
